name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2

        - name: list and read files
          run: |
            echo "My first Github Actions Job"
            ls
            pwd
            cat README.md

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Dragons are real!" >> dragon.txt
        
        - name: cat dragon
          run: cat dragon.txt
        
        # - name: list files
        #   run: ls
        
        # - name: path of my dir
        #   run: pwd
          
        # - name: cat files
        #   run: cat README.md
