name: Matrix Configuration

on:
  push:
  workflow_dispatch:


jobs:
    deploy:
      strategy:
        matrix:
            #key : value pairs of our wish 
            # 6 jobs 
            os: ["ubuntu-latest,windows-latest"]
            images: [hello-world,alpine]
      runs-on: ${{ matrix.os }}
      steps:
      - name: Echo Docker Details
        run: docker info

      - name: Run Images on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
