name: Matrix Configuration

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Removed ubuntu-20.04
        images: [hello-world, alpine]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Display Docker Info
        run: docker info

      - name: Run Docker Image
        run: docker run ${{ matrix.images }}
