name: multiple jobs

on:
  push

jobs:
    build_job1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install -y cowsay
        
        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I am DRAGON....RAWR" >> dragon.txt
        
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.5.0
          with:
            name: dragon-text-file
            path: dragon.txt
      

    test_job2:
        needs: build_job1
        runs-on: ubuntu-latest
        
        steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.8
          with:
            name: dragon-text-file

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt
    
    deploy_job3:
        needs: [ build_job1, test_job2]
        runs-on: ubuntu-latest
        steps:
        - name: Download a Build Artifact
          uses: actions/download-artifact@v4.1.8
          with:
            name: dragon-text-file

        - name: checkout Repo files
          run: ls

        - name: Deploy dragon
          run: cat dragon.txt     