# name: Exploring variables and secrets

# on:
#     push

# jobs:
#     docker:
#         runs-on: ubuntu-latest
#         steps:
#         - name: Docker Build
#           run: docker build -t 